version: '3.8'

services:
  dingding-sync:
    build: .
    container_name: dingding-sync
    restart: always
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
